### PR TITLE
Support new sonar datatype

### PR DESCRIPTION
**Pull request by romulogcerqueira**
- until this moment, only for multibeam sonars
- depends on: https://github.com/Brazilian-Institute-of-Robotics/gui-vizkit/pull/3

### CODE REVIEW

**Comment by gustavoneves12** [comment]
@romulogcerqueira, you kept the old code commented. In my opinion is not necessary to keep this codes. The github stores the code history, so, I think is not necessary keep the old code commented.

**Comment by romulogcerqueira** [comment]
Hi @gustavoneves12,

you didn't comment my last commit (https://github.com/Brazilian-Institute-of-Robotics/gui-rock_widget_collection/commit/44dcd097997d534579f38cd2a6f6df40498d76b9), but my penultimate commit (https://github.com/Brazilian-Institute-of-Robotics/gui-rock_widget_collection/commit/0a46700ed1a143af007d79e6ef58c29cbe7c8f07).

**Comment by romulogcerqueira** [comment]
Anyway, I will remove the commented code in commit https://github.com/Brazilian-Institute-of-Robotics/gui-rock_widget_collection/commit/0a46700ed1a143af007d79e6ef58c29cbe7c8f07. Thanks for your point.

**Comment by gustavoneves12** [comment]
Sorry @romulogcerqueira, it was my fault. I didn't see the last commit.

**Pull request merged**
